#include "DMProgressionComponent.h"
// Stable IDs, converging predecessors and semantic descriptions: GDD Appendix K.
// Valuation weights are provisional, shared with the situational bot choice policy.
namespace
{
const FDMEvolutionNode Nodes[] = {
    { TEXT("sapper.q.a"), TEXT("Satchel Charge"), TEXT("Place a persistent charge at a valid target location. It remains armed until detonated or removed and consumes one Prepared Charge."), 0.7f, 0.7f, 0.7f },
    { TEXT("sapper.q.b"), TEXT("Shaped Blast"), TEXT("Smaller effective blast footprint, substantially stronger central damage and Break. Favors elite, boss and priority-target demolition."), 1.0f, 0.5f, 0.2f },
    { TEXT("sapper.q.c"), TEXT("Wide Charge"), TEXT("Larger blast footprint and stronger displacement, with less concentrated central damage. Favors area control."), 0.5f, 1.0f, 0.3f },
    { TEXT("sapper.q.d"), TEXT("Breaching Charge"), TEXT("Builds on Shaped Blast. Further improves damage/Break against elites, bosses, objective objects and destructible structures."), 1.0f, 0.5f, 0.2f },
    { TEXT("sapper.q.e"), TEXT("Concussive Charge"), TEXT("Retains useful area and damage while adding strong stagger/displacement near the centre."), 0.7f, 0.7f, 0.7f },
    { TEXT("sapper.q.f"), TEXT("Daisy Chain"), TEXT("Builds on Wide Charge. Nearby prepared charges can participate in a deliberate linked detonation pattern where each blast has a valid tactical purpose. The implementation must not blindly expend charges into empty ground."), 0.5f, 1.0f, 0.3f },
    { TEXT("sapper.w.a"), TEXT("Suppressing Fire"), TEXT("Sustained cone/area fire dealing modest damage and applying strong Suppression/slow. Primary purpose is to hold enemies inside prepared zones."), 0.7f, 0.7f, 0.7f },
    { TEXT("sapper.w.b"), TEXT("Covering Fire"), TEXT("Broader/longer suppression. Allies operating through the affected space gain protection against ranged pressure."), 1.0f, 0.5f, 0.2f },
    { TEXT("sapper.w.c"), TEXT("Pin Them Down"), TEXT("Narrower area, stronger suppression and Break pressure."), 0.5f, 1.0f, 0.3f },
    { TEXT("sapper.w.d"), TEXT("Entrenched Position"), TEXT("Builds on Covering Fire. The Sapper gains a stronger defensive benefit while maintaining/fighting around the suppression zone."), 1.0f, 0.5f, 0.2f },
    { TEXT("sapper.w.e"), TEXT("Kill Zone"), TEXT("Suppressed enemies become easier to exploit with Satchel and Tripwire control/Break interactions."), 0.7f, 0.7f, 0.7f },
    { TEXT("sapper.w.f"), TEXT("Walking Fire"), TEXT("Builds on Pin Them Down. The suppression area can be swept/re-aimed while active to herd enemy movement."), 0.5f, 1.0f, 0.3f },
    { TEXT("sapper.e.a"), TEXT("Tripwire"), TEXT("Place two endpoints independently within placement constraints, creating a persistent line. The first valid crossing triggers control. Common enemies can be stopped/knocked down; elites require appropriate Break vulnerability for full hard control."), 0.7f, 0.7f, 0.7f },
    { TEXT("sapper.e.b"), TEXT("Reinforced Wire"), TEXT("Longer/more tactically useful segment and stronger stopping/Break pressure."), 1.0f, 0.5f, 0.2f },
    { TEXT("sapper.e.c"), TEXT("Detonator Wire"), TEXT("A valid Tripwire trigger can also trigger an eligible nearby Satchel Charge."), 0.5f, 1.0f, 0.3f },
    { TEXT("sapper.e.d"), TEXT("Clothesline"), TEXT("Builds on Reinforced Wire. Crossing enemies take a substantial impact and are thrown back against their approach, especially punishing charging enemies."), 1.0f, 0.5f, 0.2f },
    { TEXT("sapper.e.e"), TEXT("Prepared Ground"), TEXT("Stronger interception plus local suppression/control around the crossing point, creating a reliable setup for a nearby charge."), 0.7f, 0.7f, 0.7f },
    { TEXT("sapper.e.f"), TEXT("Resetting Fuse"), TEXT("Builds on Detonator Wire. The wire rearms after a short reset rather than being consumed and can repeatedly trigger eligible nearby charges as new legitimate opportunities arise."), 0.5f, 1.0f, 0.3f },
    { TEXT("photographer.q.a"), TEXT("Frame the Subject"), TEXT("Maintain the target/area in frame to build Exposure and reveal useful combat information."), 0.7f, 0.7f, 0.7f },
    { TEXT("photographer.q.b"), TEXT("Close Study"), TEXT("Faster single-target Exposure and deeper combat information."), 1.0f, 0.5f, 0.2f },
    { TEXT("photographer.q.c"), TEXT("Wide Angle"), TEXT("Slower Exposure generation across several enemies in a small area."), 0.5f, 1.0f, 0.3f },
    { TEXT("photographer.q.d"), TEXT("Tell-Tale Detail"), TEXT("Builds on Close Study. Framing an enemy during an important telegraph/commitment produces a major Exposure gain and a brief vulnerability opportunity."), 1.0f, 0.5f, 0.2f },
    { TEXT("photographer.q.e"), TEXT("Composition"), TEXT("Strong Exposure on the primary subject plus lesser Exposure on nearby enemies."), 0.7f, 0.7f, 0.7f },
    { TEXT("photographer.q.f"), TEXT("Group Portrait"), TEXT("Builds on Wide Angle. Enemies framed together become partially linked for later Develop effects."), 0.5f, 1.0f, 0.3f },
    { TEXT("photographer.w.a"), TEXT("Flashbulb"), TEXT("Short cone flash that disrupts nearby enemies and rapidly adds Exposure."), 0.7f, 0.7f, 0.7f },
    { TEXT("photographer.w.b"), TEXT("Blinding Flash"), TEXT("Stronger disruption, interrupt and Break pressure."), 1.0f, 0.5f, 0.2f },
    { TEXT("photographer.w.c"), TEXT("Overexpose"), TEXT("Weaker control but substantially greater Exposure gain."), 0.5f, 1.0f, 0.3f },
    { TEXT("photographer.w.d"), TEXT("Afterimage"), TEXT("Builds on Blinding Flash. Affected enemies remain impaired briefly after the initial disruption."), 1.0f, 0.5f, 0.2f },
    { TEXT("photographer.w.e"), TEXT("Caught in the Light"), TEXT("Moderate disruption/Exposure and a brief window in which affected enemies are easier to Frame."), 0.7f, 0.7f, 0.7f },
    { TEXT("photographer.w.f"), TEXT("Magnesium Burst"), TEXT("Builds on Overexpose. Very large Exposure spike against enemies currently committed to telegraphed actions."), 0.5f, 1.0f, 0.3f },
    { TEXT("photographer.e.a"), TEXT("Develop"), TEXT("Consume accumulated Exposure on the target to create an immediate payoff."), 0.7f, 0.7f, 0.7f },
    { TEXT("photographer.e.b"), TEXT("Weak Point"), TEXT("Single-target offensive branch: significant damage plus a brief vulnerability window."), 1.0f, 0.5f, 0.2f },
    { TEXT("photographer.e.c"), TEXT("Clear Evidence"), TEXT("Information branch: the resulting debuff applies to all enemies of the studied enemy type, not only the photographed specimen."), 0.5f, 1.0f, 0.3f },
    { TEXT("photographer.e.d"), TEXT("Fatal Detail"), TEXT("Builds on Weak Point. High-Exposure Develop becomes a major burst/Break event against elites and bosses."), 1.0f, 0.5f, 0.2f },
    { TEXT("photographer.e.e"), TEXT("Published Findings"), TEXT("Moderate burst on the studied target plus a shorter type-wide vulnerability/debuff."), 0.7f, 0.7f, 0.7f },
    { TEXT("photographer.e.f"), TEXT("Case File"), TEXT("Builds on Clear Evidence. The type-wide debuff is stronger and/or lasts longer."), 0.5f, 1.0f, 0.3f },
    { TEXT("medium.q.a"), TEXT("Bind Spirit"), TEXT("Attach/place a spirit on an ally, enemy or valid location; passive behaviour depends on binding target."), 0.7f, 0.7f, 0.7f },
    { TEXT("medium.q.b"), TEXT("Guardian Spirit"), TEXT("Stronger protective binding on allies/defensive locations."), 0.2f, 0.5f, 1.0f },
    { TEXT("medium.q.c"), TEXT("Haunting"), TEXT("Stronger hostile binding, hindrance and Attention generation from an enemy."), 0.3f, 1.0f, 0.5f },
    { TEXT("medium.q.d"), TEXT("Vigil"), TEXT("Builds on Guardian Spirit. The spirit can automatically intervene when its protected target is threatened."), 0.2f, 0.5f, 1.0f },
    { TEXT("medium.q.e"), TEXT("Restless Watcher"), TEXT("Moderate protection/hindrance, with added value when repositioned by Beckon."), 0.7f, 0.7f, 0.7f },
    { TEXT("medium.q.f"), TEXT("Possession"), TEXT("Builds on Haunting. At high Attention, the spirit can briefly disrupt the bound enemy or force a positional error."), 0.3f, 1.0f, 0.5f },
    { TEXT("medium.w.a"), TEXT("Beckon"), TEXT("Redirect bound spirits toward a selected point; movement/arrival can trigger effects."), 0.7f, 0.7f, 0.7f },
    { TEXT("medium.w.b"), TEXT("Procession"), TEXT("Longer/faster spirit movement; enemies crossed are briefly slowed/displaced."), 0.2f, 0.5f, 1.0f },
    { TEXT("medium.w.c"), TEXT("Calling"), TEXT("Shorter movement, stronger arrival trigger."), 0.3f, 1.0f, 0.5f },
    { TEXT("medium.w.d"), TEXT("Funeral March"), TEXT("Builds on Procession. Spirits leave a temporary route that hinders enemies and lightly protects allies crossing it."), 0.2f, 0.5f, 1.0f },
    { TEXT("medium.w.e"), TEXT("Crossroads"), TEXT("Moderate route effect plus moderate arrival trigger."), 0.7f, 0.7f, 0.7f },
    { TEXT("medium.w.f"), TEXT("Seance"), TEXT("Builds on Calling. Several spirits arriving close together trigger an additional combined effect."), 0.3f, 1.0f, 0.5f },
    { TEXT("medium.e.a"), TEXT("Intercession"), TEXT("Command the highest-Attention spirit to make a strong intervention: protect, hinder, block or displace. Normally spends substantial Attention."), 0.7f, 0.7f, 0.7f },
    { TEXT("medium.e.b"), TEXT("Guardian's Hand"), TEXT("Stronger protective intervention."), 0.2f, 0.5f, 1.0f },
    { TEXT("medium.e.c"), TEXT("Unquiet Dead"), TEXT("Stronger hostile intervention and Break pressure."), 0.3f, 1.0f, 0.5f },
    { TEXT("medium.e.d"), TEXT("Not Yet"), TEXT("Builds on Guardian's Hand. Especially valuable around a Downed investigator or active revive, improving the safety/speed of rescue without becoming a general instant revive."), 0.2f, 0.5f, 1.0f },
    { TEXT("medium.e.e"), TEXT("Between Worlds"), TEXT("Moderate protection/control and a temporary spirit presence at the intervention point."), 0.7f, 0.7f, 0.7f },
    { TEXT("medium.e.f"), TEXT("Drag Below"), TEXT("Builds on Unquiet Dead. Against sufficiently Broken enemies, violently repositions and heavily impairs the target."), 0.3f, 1.0f, 0.5f },
    { TEXT("smuggler.q.a"), TEXT("Clinch"), TEXT("Grab nearby enemy; recast to shove/throw in a chosen direction. Common enemies are fully controllable; elites require appropriate Break vulnerability."), 0.7f, 0.7f, 0.7f },
    { TEXT("smuggler.q.b"), TEXT("Lock Up"), TEXT("Stronger hold/control and Break pressure."), 1.0f, 0.5f, 0.2f },
    { TEXT("smuggler.q.c"), TEXT("Heave"), TEXT("Shorter emphasis on hold, substantially stronger throw distance and collision force."), 0.5f, 1.0f, 0.3f },
    { TEXT("smuggler.q.d"), TEXT("Make It Personal"), TEXT("Builds on Lock Up. After release the Smuggler jumps sharply up that enemy's threat table and gains a temporary damage buff specifically against that enemy."), 1.0f, 0.5f, 0.2f },
    { TEXT("smuggler.q.e"), TEXT("Rough Handling"), TEXT("Solid hold/throw; colliding the thrown enemy with another target briefly staggers both."), 0.7f, 0.7f, 0.7f },
    { TEXT("smuggler.q.f"), TEXT("Thrown Weight"), TEXT("Builds on Heave. Thrown enemies of any kind deal substantial damage and Break to enemies they collide with; heavier targets can create stronger impacts."), 0.5f, 1.0f, 0.3f },
    { TEXT("smuggler.w.a"), TEXT("Shoulder Through"), TEXT("Short charge that damages/displaces enemies and generates Momentum from meaningful contacts."), 0.7f, 0.7f, 0.7f },
    { TEXT("smuggler.w.b"), TEXT("Head Down"), TEXT("Longer charge, greater control resistance while moving and stronger first-target Momentum generation."), 1.0f, 0.5f, 0.2f },
    { TEXT("smuggler.w.c"), TEXT("Clear the Way"), TEXT("Shorter but wider charge with stronger group displacement."), 0.5f, 1.0f, 0.3f },
    { TEXT("smuggler.w.d"), TEXT("Run Them Down"), TEXT("Builds on Head Down. Triggers when the charge hits exactly one enemy; carries farther through/with that target and grants a temporary damage bonus against it."), 1.0f, 0.5f, 0.2f },
    { TEXT("smuggler.w.e"), TEXT("Bar Room Entrance"), TEXT("Moderate range/width with a brief area stagger at the primary impact."), 0.7f, 0.7f, 0.7f },
    { TEXT("smuggler.w.f"), TEXT("Bowling Through"), TEXT("Builds on Clear the Way. Successive enemies struck in the same charge suffer increasing displacement and/or Break pressure."), 0.5f, 1.0f, 0.3f },
    { TEXT("smuggler.e.a"), TEXT("Dig In"), TEXT("Brace against incoming pressure, gaining control/displacement resistance and converting incoming pressure into Momentum; can finish with a counter-shove."), 0.7f, 0.7f, 0.7f },
    { TEXT("smuggler.e.b"), TEXT("Take It on the Chin"), TEXT("Stronger mitigation/control resistance and improved Momentum generation from incoming pressure."), 1.0f, 0.5f, 0.2f },
    { TEXT("smuggler.e.c"), TEXT("Come On Then"), TEXT("Less pure mitigation, but enemies striking the Smuggler during Dig In are primed for stronger retaliation."), 0.5f, 1.0f, 0.3f },
    { TEXT("smuggler.e.d"), TEXT("Still Standing"), TEXT("Builds on Take It on the Chin. Absorbing enough pressure grants a short sustain/Health-recovery window afterward."), 1.0f, 0.5f, 0.2f },
    { TEXT("smuggler.e.e"), TEXT("Give It Back"), TEXT("Moderate protection plus a counter-shove whose strength scales with absorbed pressure."), 0.7f, 0.7f, 0.7f },
    { TEXT("smuggler.e.f"), TEXT("Your Turn"), TEXT("Builds on Come On Then. Ending Dig In produces a heavy retaliation with bonus Break against the most threatening enemy that attacked during the stance."), 0.5f, 1.0f, 0.3f },
};
}
const FDMEvolutionNode* DMEvolution::Find(EDMInvestigator Kind, uint8 Slot, uint8 Node)
{
    const int32 K = static_cast<int32>(Kind) - 1;
    return K >= 0 && K < 4 && Slot < 3 && Node < 6 ? &Nodes[K * 18 + Slot * 6 + Node] : nullptr;
}
float DMEvolution::Value(const FDMEvolutionNode& Node, float Crowding, float Danger, float Elite)
{ return Node.Offense * (1 + Elite) + Node.Control * Crowding + Node.Protection * Danger; }
